zookeeper:
  image: confluentinc/cp-zookeeper:3.2.1
  logging:
    driver: syslog
    options:
      syslog-address: tcp://data.logentries.com:16314
  environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_SERVER_ID=dongyanl
kafka:
  image: confluentinc/cp-kafka:3.2.1
  logging:
    driver: syslog
    options:
      syslog-address: tcp://data.logentries.com:16314
  ports:
    - "9092"
  links:
    - zookeeper:zk
    - kafka
  environment:
    - KAFKA_ZOOKEEPER_CONNECT=zk:2181
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    - KAFKA_ZOOKEEPER_SET_ACL=false
kafka-manager:
  logging:
    driver: syslog
    options:
      syslog-address: tcp://data.logentries.com:16314
  image: sheepkiller/kafka-manager
  ports: 
    - "9000"
  links:
    - zookeeper
  environment:
    - ZK_HOSTS=zookeeper:2181
schemaregistry:
  logging:
    driver: syslog
    options:
      syslog-address: tcp://data.logentries.com:16314
    image: confluentinc/cp-schema-registry:3.2.1
  links:
    - zookeeper
    - kafka
  environment:
    - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
    - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
    - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    - SCHEMA_REGISTRY_KAFKA_ZOOKEEPER_SET_ACL=false
kafka-rest-proxy:
  logging:
    driver: syslog
    options:
      syslog-address: tcp://data.logentries.com:16314
  image: confluentinc/cp-kafka-rest:3.2.1
  ports:
    - "8082"
  links:
    - zookeeper
    - kafka
    - schemaregistry
    - kafka-rest-proxy
  environment:
    - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_REST_LISTENERS=http://kafka-rest-proxy:8082
    - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
    - KAFKA_REST_HOST_NAME=kafka-rest-proxy
    - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schemaregistry:8081
kafka-ui:
  logging:
    driver: syslog
    options:
      syslog-address: tcp://data.logentries.com:16314
  image: landoop/kafka-topics-ui:0.9.2
  links:
    - kafka-rest-proxy
  ports:
    - "8000"
  environment:
    - KAFKA_REST_PROXY_URL=http://kafka-rest-proxy:8082
    - PROXY=true