name: IBM MQ Light Server

description: |
  A simple yet powerful AMQP-based messaging API. Write apps that run locally, in the cloud, or alongside IBM MQ.
version: 1.0.0
category: Message queues
maintainer: "Jeff Kolb <jeff.kolb@intlfcstone.com>"
minimum_rancher_version: v1.1.3
projectURL: https://developer.ibm.com/messaging/mq-light/
