version: '2'
services:
  webspheremq-datavolume:
    image: alpine:3.4
    entrypoint:
    - /bin/true
    network_mode: none
    volumes:
    - /var/mqm
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
  webspheremq-server:
    image: jeffkolb/rancher-websphere-mq:9
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: ${mq_qmgr_name}
    tty: true
    volumes_from:
    - webspheremq-conf
    - webspheremq-datavolume
    ports:
    - ${ampq_listen_port}:1414
    labels:
      io.rancher.sidekicks: webspheremq-conf, webspheremq-datavolume
      io.rancher.container.hostname_override: container_name
  webspheremq-conf:
    image: jeffkolb/rancher-websphere-mq-conf:1
    entrypoint:
    - /bin/true
    network_mode: none
    volumes:
    - /etc/mqm/config.mqsc
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
  
  webspheresender-app:
    image: jeffkolb/rancher-websphere-sender:1
    environment:
      LICENSE: accept
    tty: true
    links:
    - webspheremq-server:mqfull
    volumes_from:
    - webspheresender-conf
    ports:
    - ${sender_ui_port}:9180
    - 9443
    labels:
      io.rancher.sidekicks: webspheresender-conf
      io.rancher.container.hostname_override: container_name
  webspheresender-conf:
    image: jeffkolb/rancher-websphere-sender-conf:1
    entrypoint:
    - /bin/true
    network_mode: none
    volumes:
    - /opt/ibm/wlp/usr/servers/defaultServer/server.xml
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
  
  webspherereceiver-app:
    image: jeffkolb/rancher-websphere-receiver:1
    environment:
      LICENSE: accept
    tty: true
    links:
    - webspheremq-server:mqfull
    volumes_from:
    - webspherereceiver-conf
    ports:
    - ${receiver_ui_port}:9180
    - 9443
    labels:
      io.rancher.sidekicks: webspherereceiver-conf
      io.rancher.container.hostname_override: container_name
  webspherereceiver-conf:
    image: jeffkolb/rancher-websphere-receiver-conf:1
    entrypoint:
    - /bin/true
    network_mode: none
    volumes:
    - /opt/ibm/wlp/usr/servers/defaultServer/server.xml
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
