.catalog:
    name: "Graylog"
    version: "v2.1.1-1"
    description: "Open source log management that actually works."
    questions:
        - variable: graylog_password
          description: "Password in sha2"
          label: "SHA2 Password"
          type: "string"
          required: true
          default: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        - variable: graylog_secret
          description: "Password secret"
          label: "Password secret"
          type: "string"
          default: "somepasswordpepper"
          required: true
        - variable: graylog_fqdn
          description: "IP or domain name"
          label: "FQDN"
          type: "string"
          required: true
          default: "127.0.0.1"
        - variable: es_service
          description: "Service ElasticSearch"
          label: "Service ElasticSearch"
          type: "service"
          required: true
