name: Apache Kafka
description: |
  (Experimental) Kafka cluster JEFFK
version: 0.10.1.0-rancher1
category: Clustering
maintainer: "Jeff Kolb <jeff.kolb@intlfcstone.com>"
minimum_rancher_version: v0.59.0
license: 
projectURL: https://github.com/junkiebev/catalog-dockerfiles