name: Apache Kafka
description: Kafka cluster with management and UI
version: 0.10.2.0-rancher
category: Clustering
maintainer: "Dongyan Li<dongyan.li@intlfcstone.com>"
minimum_rancher_version: v0.59.0
license: 
projectURL: https://github.com/akking/community-catalog