.catalog:
  name: "IBM MQ Light"
  version: 1.0.0
  description: |
  IBM MQ Light server.
  uuid: IBMMQLIGHT-JeffK1
  minimum_rancher_version: v1.1.3
  questions:

version: '2'
services:
  mqlight-datavolume:
    scale: 1
    start_on_create: true
  mqlight-server:
    scale: 1
    start_on_create: true

